### ISSUE TITLE
Cookies on virgin media player not being accepted

### ISSUE THREAD

**Issue by pythonkenyard** [fullonrager/rte-L3#1]
Not sure if new. Seems the accept cookies page is not being accepted, so it's pulling the mpd but can't hit play to get keys.?

**Comment by fullonrager** [comment]
The cookies on the Virgin Media Player do not need to be accepted nor does the media need to be played as the keys, if any, are extracted simply from the page loading. Are you sure the media doesn't stream unencrypted?

**Comment by pythonkenyard** [comment]
I'll try it again later mate and let you know. I tried 3 or 4 times and got the warning. I only tried proceeding once and it failed.

**Comment by fullonrager** [comment]
If it doesn't work link the episode and I can look into it.
