### ISSUE TITLE
Subtitles?

### ISSUE THREAD

**Issue by Erisceres** [fullonrager/rte-L3#2]
Interesting educational tool. I wonder if this could be updated to include the ability to download subtitles?

**Comment by fullonrager** [comment]
I can add subtitle support. Can anyone confirm if TG4 or Virgin have subtitles? I don't see an option anywhere.

**Comment by Erisceres** [comment]
Yes, most (not all) TG4 videos have subtitles. If you go into the MPD file and search for "text", you'll find the subtitles which could be extracted by the script. For now, I can do it manually.

**Comment by fullonrager** [comment]
Alright, I've finished writing support for RTÉ and now TG4. Some episodes on RTÉ don't have a subtitles link in their XML despite the episode having subtitles however most do. Just want to fix up some parts and if I still don't see any video on Virgin with subtitles I'll push the update tomorrow.

**Comment by fullonrager** [comment]
Subtitle support now available in v1.2.2.
