### ISSUE TITLE
Getting quicktime instead of h264

### ISSUE THREAD

**Issue by rieran** [fullonrager/rte-L3#3]
Rte-L3
1.2.2

Happening since
14/03
Definitely was working mid last week

Chrome
Version 89.0.4389.90 (Official Build) (64-bit)

Driver
Version 89.0.4389.23

Input
.\rtel3.py https://www.rte.ie/player/series/smother/SI0000008292?epguid=AI000003394

Output
***  RTÉ Player Downloader (rte-L3 v1.2.2)  ***
***        Developed by fullonrager         ***

Loading page...
Accepting necessary cookies...
Attempting to click play button...
Searching for MPD URL...
Found subtitles, will merge into video.

Video title = Smother S1 E2

Found MPD URL: https://vod.rte.ie/rte/vod-d/RTE_Prod_-_Prod/820/556/AI000003394/M3727783-1615568463582.ism/.mpd?available=1615760940&expiry=1772755200&ip=<ip_snip>&token1=a18474a85fea8dd90f66a68c70b7b57f023850a39ef9c82d54d424a84969a5ca&filter=systemBitrate%3C%3D7000000&hls_fmp4=true

Failed to get decryption key.
It's possible that this media streams unencrypted.

Would you like to download anyway? (y/n):

MediaInfo of grabbed file, not playable in vlc

General
Unique ID                                : 34611947294209503098707783748563341478 (0x1A0A04C12EFD53582E79049BE09190A6)
Complete name                            : 
Format                                   : Matroska
Format version                           : Version 4
File size                                : 2.14 GiB
Duration                                 : 50 min 19 s
Overall bit rate                         : 6 079 kb/s
Encoded date                             : UTC 2021-03-15 06:52:17
Writing application                      : mkvmerge v35.0.0 ('All The Love In The World') 64-bit
Writing library                          : libebml v1.3.9 + libmatroska v1.5.2

Video
ID                                       : 1
Format                                   : V_QUICKTIME
Codec ID                                 : V_QUICKTIME
Duration                                 : 50 min 19 s
Bit rate                                 : 6 013 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Bits/(Pixel*Frame)                       : 0.116
Stream size                              : 2.11 GiB (99%)
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AAC LC SBR PS
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication and Parametric Stereo
Commercial name                          : HE-AACv2
Format settings                          : Explicit
Codec ID                                 : A_AAC-2
Duration                                 : 50 min 19 s
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Stream size                              : 23.0 MiB (1%)
Default                                  : Yes
Forced                                   : No

**Comment by fullonrager** [comment]
The video you tried downloading does in fact stream encrypted, hence resulting in the unplayable output. The reason the script failed to grab the decryption key is because Chrome version 89 patches the decryptor (intentionally or otherwise). I will be pushing an update soon to check the installed Chrome version and to quit the script if it's above version 88. For now, you can downgrade Chrome manually and continue using v1.2.3.

**Comment by pythonkenyard** [comment]
Cheers. Was wondering this myself.

**Comment by fullonrager** [comment]
Issue addressed with version checker in v1.2.4.
